version: '3' # 目前使用的版本
services: # services 關鍵字後面列出 web, redis 兩項專案中的服務
    php:
        image: ocard/php8.1-fpm-alpine:1.1
        container_name: "${PROJECT_NAME}-php-fpm"
        environment:
            - TZ=Asia/Taipei
        volumes:
            - ${PROJECT_PATH}:/var/www/html
            - ./entrypoint.sh:/entrypoint.sh
            - ./main_crontabs/schedule:/etc/crontabs/schedule # alpine crontab 使用
            - ./main_crontabs/root:/etc/crontabs/root # alpine crontab 使用
            - ${PHP_ENV_PATH}:/var/www/html/.env
            - ${PHP_LOG_PATH}:/var/log/php
            - ${PHP_CONFIG_PATH}:/usr/local/etc/php/conf.d/custom.ini
        command: /bin/sh -c "/entrypoint.sh "
        restart: always  
        networks:
            - richmenu
    nginx:
        image: 204075225894.dkr.ecr.ap-northeast-1.amazonaws.com/ocard/nginx:1.0
        container_name: "${PROJECT_NAME}-nginx"
        ports:
            - "${NGINX_HTTP_PORT}:80"
            - "${NGINX_HTTPS_PORT}:443"
        links:
            - "php"
        volumes:
            - ${PROJECT_PATH}:/usr/share/nginx/html
            - ./nginx/conf.d:/etc/nginx/conf.d:ro
            - /var/ocard/nginx/logrotate.conf:/etc/logrotate.d/nginx
            - ${NGINX_SSL_PATH}:/etc/nginx/ssl
            - ${NGINX_LOG_PATH}:/var/log/nginx
        restart: always  
        networks:
            - richmenu


networks:
    richmenu:
        ipam:
            driver: default
            config:
                - subnet: 192.168.247.0/24
